"""Add difficulty column to flashcards

Revision ID: 2bbf9b9344f4
Revises: bc64ef5e3d2b
Create Date: 2025-03-03 13:55:29.685941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bbf9b9344f4'
down_revision = 'bc64ef5e3d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hint', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('hint')

    # ### end Alembic commands ###
