"""add cascade delete for flashcard progress

Revision ID: aec229f47684
Revises: 073cb3b850a6
Create Date: 2025-03-09 21:01:29.944091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec229f47684'
down_revision = '073cb3b850a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_constraint('progress_flashcard_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'flashcards', ['flashcard_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('progress_flashcard_id_fkey', 'flashcards', ['flashcard_id'], ['id'])

    # ### end Alembic commands ###
